apply plugin: 'com.android.application'

android {
    namespace 'com.operit.timetable'
    compileSdk 35

    defaultConfig {
        applicationId "com.operit.timetable"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            java.srcDirs = ["src/main/java"]
            res.srcDirs = []
            assets.srcDirs = ["src/assets"]
            manifest.srcFile "src/main/AndroidManifest.xml"
        }
    }
}